config/routes.rb
Rails.application.routes.draw do
  resources :locations

  root 'locations#new'

end

app/models/location.rb
class Location < ActiveRecord::Base
  geocoded_by :full_street_address
  after_validation :geocode

  ALL_CITIES = [
                'Atlanta',
                'Alpharetta',
                'Avondale Estates',
                'Chamblee',
                'Clarkston',
                'College Park',
                'Decatur',
                'Doraville',
                'Dunwoody',
                'East Point',
                'Ellenwood',
                'Fairburn',
                'Forest Park',
                'Hapeville',
                'Jonesboro',
                'Lake City',
                'Lovejoy',
                'Lithonia',
                'Morrow',
                'Palmetto',
                'Riverdale',
                'Roswell',
                'Sandy Springs',
                'Stone Mountain',
                'Union City'
                ]


  def full_street_address
    "#{street_address}, #{city}, GA"
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  include LocationsHelper

  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    #MARTY API URL
    source_url = "http://developer.itsmarta.com/BRDRestService/RestBusRealTimeService/GetAllBus"

    @buses = fetch_buses_from_api(source_url)

    #Only keep the ones that are near buy

    @buses.select! do |bus|
      is_nearby?(@location.latitude, @location.longitude, bus["LATITUDE"], bus["LONGITUDE"])
    end
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:street_address, :city, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
  #Parse the API data and store it so that we can work with it
  def fetch_buses_from_api(source_url)
    http = Net::HTTP.get_response(URI.parse(source_url))
    data = http.body
    JSON.parse(data)
  end

  def is_nearby?(user_lat, user_long, bus_lat, bus_long)
    # Maximum Distance in degrees
    max_distance = 0.01 #  0.01 degrees is about half a mile

    difference_latitudes = user_lat - bus_lat.to_f
    difference_longitudes = user_long - bus_long.to_f

    distance = Math.sqrt(difference_latitudes ** 2 + difference_longitudes ** 2)

    distance <= max_distance
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BuseyLock</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street_address %><br>
    <%= f.text_field :street_address, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>Street address</th>
      <th>City</th>
      <th>Lattitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.street_address %></td>
        <td><%= location.city %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>Busey Lock</h1>

<p>
  Give us you current location, or an intersection and we'll let you know if there is a bus near by!
</p>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"> <%= notice %> </p>

<h1>Busey Lock is Locked!</h1>

<h3 class="text-muted">Your Current Location:</h3>

<p class="text-muted">

<%= @location.full_street_address %> <small> <%= link_to fa_icon('pencil', text: 'Edit'), edit_location_path(@location) %></small>

</p>

<div id="map-canvas" style="height: 500px; width: 500px; margin: 0; padding: 0;"></div>


<h3>The closest buses are...</h3>
  <% @buses.each do |bus| %>
    <p>
      <strong> Route: </strong> <%= bus["ROUTE"] %> <%= bus["DIRECTION"] %><br>
      <strong> Bus Number: </strong> <%= bus["VEHICLE"] %><br>
      <strong> Next Stop: </strong> <%= bus["TIMEPOINT"] %><br>
    </p>
  <% end %>

  <% if @buses.empty? %>
    <p>
      Not really that close. <%= link_to 'edit your location', edit_location_path(@location) %>
    </p>
  <% end %>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_maps_api_key'] %>"></script>

<script type="text/javascript">
  function initialize() {
    var myLocation = new google.maps.LatLng(<%= @location.latitude %>, <%= @location.longitude %>);

    var mapOptions = {
        center: myLocation,
        zoom: 15
    };

    var map = new google.maps.Map(document.getElementById('map-canvas'),
        mapOptions);

    var personIcon = "<%= image_path 'man_icon.png' %>";

    var myMarker = new google.maps.Marker({
        position: myLocation,
        map: map,
        animation: google.maps.Animation.DROP,
        title: 'You are Here',
    });

    var nearbyBuses = <%= raw @buses.to_json %>;

    nearbyBuses.forEach(function (element) {
      var busLocation = new google.maps.LatLng(element['LATITUDE'], element['LONGITUDE']);

      var busMarker = new google.maps.Marker({
        position: busLocation,
        map: map,
        animation: google.maps.Animation.DROP,
        title: element['VEHICLE']
      });

      var contentString = '<div id="content">'+
              '<h2>Bus '+ element['VEHICLE']+' '+element['DIRECTION']+'</h2>'+
              '<div id="bodyContent">'+
                '<p>Next Stop: '+ element['TIMEPOINT'] +'</p>'+
              '</div>'+
            '</div>';

            var infoWindow = new google.maps.InfoWindow({
              content: contentString
            });

            google.maps.event.addListener(busMarker, 'click', function() {
              infoWindow.open(map, busMarker);
            });
    });
  }
  google.maps.event.addDomListener(window, 'load', initialize);

</script>